/root/ecg_ai/FocusECG/FocusECG/finetune_test.py:119: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt_path, map_location='cpu')
cuda
cuda
Namespace(all_encode_norm_layer='LayerNorm', batch_size=512, ckpt_path='/root/ecg_ai/FocusECG/FocusECG/ckpt/pre_train/icentiallk-p01/FocusMae/202501070232/min_val_loss=23.90247344970703.pth', class_n=5, classifier_head_name='mlp_v1', data_standardization=True, dataset_name='cpsc2018', decoder_depth=8, decoder_embed_dim=64, decoder_num_heads=8, device=device(type='cuda'), early_stop_patience=30, embed_dim=256, encoder_depth=48, encoder_num_heads=16, learning_rate=0.0001, mask_ratio=0.75, mask_type='period', max_epoch_num=1000, mlp_ratio=2, model_name='FocusMae', norm_layer='LayerNorm', num_input_channels=1, num_layers=48, patch_length=50, patch_size=50, patch_stride=50, pretrain_model_freeze=True, scheduler_factor=0.8, scheduler_min_lr=1e-08, scheduler_patience=20, self_attn=True, self_attn_heads=16, signal_length=2500, task='finetune', test_data_path='/root/data/p1-2_people2000_segmentall_sample_step100_data/index_60-80k_step:1.txt', train_data_path='/root/data/cpsc2018/train.txt', use_cls_token=True, use_positional_encoding=True, val_data_path='/root/data/cpsc2018/val.txt', val_every_n_steps=40, weight_decay=0.001)
training:   0%|          | 0/11 [00:00<?, ?it/s]                                                Traceback (most recent call last):
  File "main.py", line 78, in <module>
    run_finetune(args)
  File "/root/ecg_ai/FocusECG/FocusECG/finetune_test.py", line 177, in run_finetune
    for batch_idx, batch in enumerate(prog_iter):
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ecg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/ecg_ai/FocusECG/FocusECG/dataset.py", line 109, in __getitem__
    target = torch.tensor(self.label_map[data[1]], dtype=torch.long)
KeyError: 'STD'

